"""
Backup analyzer for Frappe .sql.gz files.

Provides:
  - analyze_backup(path) -> table stats + noise flags
  - filter_sql_stream(input, skip_tables, output) -> filtered SQL stream
"""
from __future__ import annotations

import gzip
import re
from typing import IO

# Tables that are safe to skip during restore — they are large, noisy,
# and fully regenerated by Frappe after restore.
NOISE_TABLES = {
    "tabActivity Log",
    "tabAccess Log",
    "tabError Log",
    "tabEmail Queue",
    "tabEmail Queue Recipient",
    "tabVersion",
    "tabRoute History",
    "tabScheduled Job Log",
    "tabWeb Page View",
    "tabView Log",
    "tabEvent Sync Log",
    "tabEnergy Point Log",
    "tabNotification Log",
    "tabDocument Share Key",
}

_DUMP_HEADER_RE = re.compile(r"^-- Dumping data for table `(.+?)`")
_INSERT_RE = re.compile(r"^INSERT INTO `(.+?)`")
# Count VALUE tuples: each (...) is one row
_TUPLE_RE = re.compile(r"\(")


def analyze_backup(path: str) -> dict:
    """
    Stream-scan a .sql.gz backup file and return table statistics.

    Returns:
        {
            "tables": {
                "tabActivity Log": {"rows": 50000, "noise": True},
                "tabCustom Field": {"rows": 200, "noise": False},
            },
            "noise_tables": ["tabActivity Log", ...],
            "noise_row_count": 50000,
            "total_row_count": 50200,
        }
    """
    tables: dict[str, dict] = {}
    current_table: str | None = None

    opener = gzip.open if path.endswith(".gz") else open
    with opener(path, "rt", encoding="utf-8", errors="replace") as f:
        for line in f:
            # Detect table section header
            m = _DUMP_HEADER_RE.match(line)
            if m:
                current_table = m.group(1)
                if current_table not in tables:
                    tables[current_table] = {"rows": 0, "noise": current_table in NOISE_TABLES}
                continue

            # Count rows in INSERT statements
            if current_table and line.startswith("INSERT INTO"):
                # Count value tuples by counting opening parens after VALUES keyword
                # Works for both single-line and multi-line inserts
                row_count = line.count("),(") + (1 if "(" in line else 0)
                # More accurate: count top-level ( that start a row tuple
                # For simplicity, count commas between ) and ( as row separators
                # Pattern: VALUES (row1),(row2),(row3)
                # Split on "VALUES" and count tuples
                if "VALUES" in line.upper():
                    after_values = line[line.upper().index("VALUES") + 6:]
                    # Count the number of '),(' separators + 1 = row count
                    row_count = after_values.count("),(") + 1
                    tables[current_table]["rows"] += row_count
                else:
                    # Multi-line INSERT continuation — count top-level tuples
                    # Each line starting with ( is a row
                    tables[current_table]["rows"] += line.count("),(") + (
                        1 if line.strip().startswith("(") else 0
                    )

    noise_tables = [t for t in tables if tables[t]["noise"] and tables[t]["rows"] > 0]
    noise_row_count = sum(tables[t]["rows"] for t in noise_tables)
    total_row_count = sum(t["rows"] for t in tables.values())

    return {
        "tables": tables,
        "noise_tables": noise_tables,
        "noise_row_count": noise_row_count,
        "total_row_count": total_row_count,
    }


def filter_sql_stream(
    input: IO[str],
    skip_tables: list[str],
    output: IO[str],
) -> None:
    """
    Stream SQL from input, write to output, skipping INSERT statements
    for any table in skip_tables.

    - CREATE TABLE is always kept (schema must exist even for empty tables)
    - LOCK/UNLOCK TABLES kept (MariaDB requires them around data blocks)
    - INSERT INTO <skipped_table> lines are dropped entirely
    - Multi-line INSERTs are handled: once we see INSERT for a skipped table,
      we drop all lines until the statement ends with ';'
    """
    skip_set = set(skip_tables)
    skipping = False  # True when inside a skipped INSERT block

    for line in input:
        # Detect start of an INSERT statement
        m = _INSERT_RE.match(line)
        if m:
            table = m.group(1)
            if table in skip_set:
                skipping = True
            else:
                skipping = False

        if skipping:
            # Drop this line; reset skipping when statement ends
            if line.rstrip().endswith(";"):
                skipping = False
            continue

        output.write(line)
